name: spaces checkout run
author: work-spaces
description: Installs spaces, runs spaces checkout, then spaces run
branding:
  icon: play
  color: purple

inputs:
  checkout:
    description: Arguments to pass to spaces checkout
    required: true
  run:
    description: Arguments to pass to spaces run
    required: true

runs:
  using: composite
  steps:
    - uses: work-spaces/install-spaces@v0.15.26

    - id: create-workspace
      run: |
        WORKSPACE_DIR="spaces-run-$(date +%Y%m%d-%H%M%S)-$$"
        mkdir -p "$WORKSPACE_DIR"
        echo "dir=$WORKSPACE_DIR" >> $GITHUB_OUTPUT
      shell: bash

    - run: |
        spaces checkout-repo --name=${{ steps.create-workspace.outputs.dir }} ${{ inputs.checkout }}
      shell: bash

    - run: |
        cd ${{ steps.create-workspace.outputs.dir }}
        spaces run ${{ inputs.run }}
      shell: bash

    - if: always()
      run: |
        if [ -d "$WORKSPACE_DIR" ]; then
          rm -rf "$WORKSPACE_DIR"
          echo "Cleaned up workspace directory: $WORKSPACE_DIR"
        fi
      shell: bash
      env:
        WORKSPACE_DIR: ${{ steps.create-workspace.outputs.dir }}
